# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20161001_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='File'),
        ),
    ]
