# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='file',
        ),
        migrations.AddField(
            model_name='note',
            name='files',
            field=models.ManyToManyField(to='notes.File'),
        ),
    ]
