# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20161003_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Note'),
        ),
    ]
