# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20161003_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='model',
            new_name='note',
        ),
    ]
