# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20161003_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='Image'),
        ),
    ]
